---
- hosts: all # ubuntu-devbox
  sudo: true
  user: vagrant # (use default: vagrant) 
  sudo_user: root  # (use default: root)
  vars:
    host_name: ubuntu-vagrant-devbox
    user: vagrant
    git_username: Creative_Dev  # update
    git_email: your@bitbucket.acc  # update
  tasks:
    #- command: pip --no-input install git+ssh://git@bitbucket.org/trapeze/boulanger.git#egg=boulanger
    - name: allow host forwarding
      template:
        src=templates/ssh_config.j2
        dest=/home/{{ user }}/.ssh/config
    - name: change ssh folder permissions
      file: path=/home/vagrant/.ssh owner={{ user }} group={{ user }} state=directory recurse=yes
    # does not work, hangs ...
    #  pip: name=git+ssh://git@bitbucket.org/trapeze/boulanger.git#egg=boulanger
    - name: add node.js repo to /etc/apt-/sources.list/
      apt_repository: repo=ppa:chris-lea/node.js
    - name: add ubuntugis repo to /etc/apt/sources.list/
      apt_repository: repo=ppa:ubuntugis/ubuntugis-unstable
    - name: update apt
      apt: update_cache=yes
    - apt: upgrade=safe
    - name: install image libraries
      apt: name={{ item }} state=present
      with_items:
        - libjpeg-dev
        - zlib1g-dev
        - libfreetype6-dev
    - name: install required python
      apt: name={{ item }} state=present
      with_items:
        - python-pip 
        - python-dev 
        - build-essential
        - python-setuptools
        - openssh-server
        - python-imaging
        - ipython
        - python-docutils
        - python-software-properties
        - python-mapscript
        - python-crypto
        - bash-completion
    - name: install avahi, exim, git, subversion, nginx, nodejs, vim
      apt: name={{ item }} state=present
      with_items:
        - avahi-daemon
        - exim4
        - git-core
        - git-svn
        - subversion
        - vim
        - nodejs
    # TODO: nnot working
    #- name: install npm packages
    #  command: npm install -g $item
    #  with_items:
    #    - grunt-cli
    #    - grunt-init
    #    - bower
    - name: install npm packages
      npm: name={{ item }} global=yes
      with_items:
        - grunt-cli
        - bower
        - grunt-init
    - name: install postgres postgis
      apt: name={{ item }} state=present
      with_items:
        - postgresql-client-common
        - postgresql
        - postgis 
        - python-psycopg2
        - python-gdal
        - libproj-dev
        - gdal-bin
        - libpq-dev 
        - postgresql-9.3-postgis-scripts
    - name: start postgres and enable at boot
      service: name=postgresql
               enabled=yes
               state=started      
    - name: install unattended upgrades package
      apt: name=unattended-upgrades
      notify:
        - dpkg reconfigue unattended
    - pip: name=setuptools
    - pip: name=pip version=6.0.6
    - pip: name=Pillow
    - pip: name=fabric
    - pip: name=gunicorn
    - pip: name=fogbugz
    - pip: name=BeautifulSoup
    - name: create locale, ensure exists
      locale_gen: name=en_CA.UTF-8 state=present
    - command: update-locale LANG=en_CA.UTF-8 # usr/sbin
    - name: update hostname
      hostname: name={{ host_name }}
    - name: create gitconfig
      sudo: false
      template: 
        src=templates/gitconfig.j2
        dest=/home/{{ user }}/.gitconfig
    - name: set timezone variables
      copy: content='America/Toronto'
            dest=/etc/timezone
            owner=root
            group=root
            mode=0644
            backup=yes
      notify:
        - update timezone
    - name: update bashrc PYTHONPATH
      lineinfile:
        dest=/home/{{ user }}/.bashrc
        line="export PYTHONPATH=.:..:../lib"
  handlers:
    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
    - name: dpkg reconfigure
      command: >
        dpkg-reconfigure unattended
        --frontend noninteractive
        -plow unattended-upgrades
    - name: restart postgresql
      service: name=postgresql state=restarted
    - name: restart nginx
      service: name=nginx state=restarted
    - name: update exim4.conf
      shell: /usr/sbin/update-exim4.conf
